import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import ReactQueryProvider from "@/utiils/ReactQueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Animetastic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> <NextTopLoader />
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
